# Generated by Django 4.0.3 on 2022-03-22 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Plain Text'), (1, 'Common Mark'), (2, 'Image Link'), (3, 'Image File')], default=0)),
                ('title', models.TextField(default='title')),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('visibility', models.IntegerField(choices=[(0, 'Public'), (1, 'Friends'), (2, 'Private')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unlisted', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='post image')),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, null=True, size=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
