# Generated by Django 3.2.10 on 2022-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[('text/markdown', 'Commonmark'), ('text/plain', 'Plain'), ('application/base64', 'Base64'), ('image/png;base64', 'Png'), ('image/jpeg;base64', 'Jpeg')], default='text/plain'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(choices=[('Public', 'Public'), ('Friends', 'Friends')], default='Public'),
        ),
    ]
