# Generated by Django 3.2.10 on 2022-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220323_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.TextField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.TextField(choices=[('Public', 'Public'), ('Friends', 'Friends')], default='Public'),
        ),
    ]
