# Generated by Django 3.2.10 on 2022-03-23 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_address', models.TextField()),
                ('auth', models.TextField()),
            ],
        ),
    ]
