# Generated by Django 3.2.10 on 2022-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='author',
            field=models.TextField(),
        ),
    ]
