# Generated by Django 3.2.10 on 2022-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='requesting_author',
            field=models.TextField(),
        ),
    ]
