# Generated by Django 3.2.10 on 2022-04-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0003_auto_20220402_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
